import {gql} from "apollo-boost";

export const GET_TUTORING_POSTS = gql`query
{
    tutorPostFeed(lastOffset:0,limit:10){
        id,
        title,
        fee,
        lastUpdated,
        keyConcepts,
        timeAvailability,
        finishBy,
        materials,
        user{
            id,
            lastName,
            firstName,
            major,
            year,
        }
        preferredSoftware,
        description,
        topics{
            id,name
        }
    }

    me{
        id
        followedTopics{
            id
            name
            thumbnail
        }
        tutorCard{
            id
        }
        myTutorPosts{
            id,
            title,
            fee,
            lastUpdated,
            keyConcepts,
            timeAvailability,
            finishBy,
            materials,
            user{
                id,
                lastName,
                firstName,
                major,
                year,
            }
            applications{
                id
                university{
                    id
                    name
                }
                major,
                year,
                lastName
                firstName
                tutorCard{
                    id
                    year
                    major
                    skills
                    timeAvailability
                    preferredSoftware
                    details
                }
            }
            preferredSoftware,
            description,
            topics{
                id,name
            }
        }
    }
}
`;

export const SEARCH_TUTORING_POSTS = gql`query($searchString:String)
{
    searchTutorPost(lastOffset:0,limit:10,searchString:$searchString){
        id,
        title,
        fee,
        lastUpdated,
        user{
            id,
            lastName,
            firstName,
            major,
            year,
        }
        preferredSoftware,
        description,
        topics{
            id,name
        }
    }

}
`;

export const MY_POSTS = gql`query
{
    me{
        id

    }
}
`;