// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:1ecde476-4652-49a2-9b45-ab2c04946758",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_cd4fZiceG",
    "aws_user_pools_web_client_id": "43bqonj4u0bojdvmk40e3dcaeg",
    oauth: {
        domain: 'your_cognito_domain',
        redirectSignIn: '/home',
        redirectSignOut: '/signIn',
        responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
    }
};


export default awsmobile;
